//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationShop.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int Id { get; set; }
        public int IdApp { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string CommentText { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Applications Applications { get; set; }
    }
}
